{{- if gt (.Values.pdp.replicas | int) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  {{- if .Values.useStandardHelmNamingConventions }}
  name: {{ include "..fullname" . }}
  {{- else }}
  name: permitio-pdp-pdb
  {{- end }}
  labels:
    {{- include "pdp.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- else if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- else }}
  minAvailable: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "pdp.selectorLabels" . | nindent 6 }}
{{- end }}
