{{- if and .Values.openshift.enabled .Values.openshift.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.openshift.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pdp.labels" . | nindent 4 }}
{{- end }}

{{- if and .Values.openshift.enabled .Values.openshift.serviceAccount.create }}
---
# RoleBinding to allow the ServiceAccount to use the specified SCC
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.openshift.serviceAccount.name }}-scc-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pdp.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.openshift.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:{{ .Values.openshift.serviceAccount.sccName }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
