repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml
        exclude: "charts/"
      - id: end-of-file-fixer
        exclude: "charts/"
      - id: trailing-whitespace
