repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml
        exclude: "helm/"
      - id: end-of-file-fixer
        exclude: "helm/"
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
#  - repo: https://github.com/pycqa/isort
#    rev: 5.10.1
#    hooks:
#      - id: isort
