name: Deploy sidecar for client
on:
  workflow_dispatch:
    inputs:
      pdp_key:
        description: 'Provide a PDP_API_KEY env var'
        required: true
        type: string
      name:
        description: 'Provide the name of the sidecar'
        required: true
        type: string

env:
  AWS_REGION: "us-east-2"

permissions:
  id-token: write
  contents: write

jobs:
  deploy-new-sidecar:
    runs-on: ubuntu-latest
    env:
      SIDECAR_NAME: ${{ inputs.name }}
      PDP_API_KEY: ${{ inputs.pdp_key }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: AWS Auth - Assume OIDC Github Role
        uses: aws-actions/configure-aws-credentials@811cf67cbe28fd16d5a320c029542d8a3ae178c0 # v1.6.1
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: githubactions

      - name: Amazon ECR Login - Root Account
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@5a88a04c91d5c6f97aae0d9be790e64d9b1d47b7 # v1

      - name: Set Kubernetes context
        uses: Azure/k8s-set-context@0b53301dcc7ddd3f6d35f97fb67228ac4e5ab2fd # v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          context: prod

      - name: Helm Dependency Build
        shell: bash
        env:
          NAMESPACE: permitio
        run: helm dependency build ./helm/

      - name: Helm Install
        shell: bash
        env:
          NAMESPACE: sidecars
          CHART_DIR: ./helm
          DNSHOST: ${{ env.SIDECAR_NAME }}-sidecar.permit.io
        run: |
          helm upgrade --install \
            -f "$CHART_DIR/values-prod.yaml" \
            "$SIDECAR_NAME-sidecar" "$CHART_DIR" \
            -n "$NAMESPACE" \
            --wait \
            --set expose.dnsHostName="$DNSHOST" \
            --set config.env.PDP_API_KEY="$PDP_API_KEY"
