name: Build and Push PDP Docker Image Manually

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: 'The tag for the image'
        type: string

jobs:
  build-and-push-pdp:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ inputs.tag }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: actions/checkout@v3
      with:
        repository: permitio/permit-opa
        ref: main
        path: './permit-opa'
        token: ${{ secrets.CLONE_REPO_TOKEN }}

    - name: Pre build PDP
      run: |
        echo "${IMAGE_TAG}" | cut -d '-' -f 1 > permit_pdp_version
        rm -rf custom
        mkdir custom
        build_root="$PWD"
        cd ./permit-opa
        find * -name '*go*' -print0 | xargs -0 tar -czf "$build_root"/custom/custom_opa.tar.gz --exclude '.*'
        if [[ "${IMAGE_TAG}" != *alpha* ]]; then
          echo "Alpha version not detected, exiting..."
          exit 1
        fi

    - uses: robinraju/release-downloader@v1
      with:
        repository: permitio/datasync
        latest: true
        fileName: factstore_server*
        token: ${{ secrets.CLONE_REPO_TOKEN }}
        out-file-path: "factstore_server"

    - name: Build and push PDP image - (pre-release)
      uses: docker/build-push-action@v5
      with:
        push: true
        context: .
        platforms: linux/amd64,linux/arm64
        tags: permitio/pdp-v2:${{ inputs.tag }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
